Copyright = "All rights reserved - 2017-2019"
baseURL = "https://nikolinden.netlify.com/"
canonifyurls = true
languageCode = "ru-RU"
paginate = 8
theme = "casper"
title = "Фестиваль Николин день"
[params]
author = "Клуб Арт'Эриа"
authorbio = "ПАКИ"
authorlocation = "Москва, Россия"
authorwebsite = "http://clubarteria.ru"
cover = "images/cover.jpg"
description = "Фестиваль творчества в честь праздника Николы Вешнего"
googleAnalyticsUserID = ""
hideHUGOSupport = false
hjsStyle = "default"
logo = "images/logo.png"
[taxonomies]
tag = "tags"
[params.social]
twitter = "clubarteria"
[[menu.social]]
identifier = "vkontakte"
pre = "<i class='fa fa-vk'></i>"
url = "https://vk.com"
weight = 1
