Copyright = "All rights reserved - 2017-2019"
baseURL = "https://nikolinden.netlify.com/"
canonifyurls = true
languageCode = "ru-RU"
paginate = 5
theme = "casper"
title = "Фестиваль Николин день"
[[menu.main]]
identifier = "prog"
name = "Программа"
pre = "<i class='fa fa-heart'></i>"
url = "/programma/"
weight = 4
[[menu.social]]
identifier = "vkontakte"
pre = "<i class='fa fa-vk'></i>"
url = "https://vk.com"
weight = 1
[params]
author = "Клуб Арт'Эриа"
authorbio = "ПАКИ"
authorlocation = "Москва, Россия"
authorwebsite = "http://clubarteria.ru"
cover = "images/cover.jpg"
description = "Фестиваль творчества в честь праздника Николы Вешнего"
googleAnalyticsUserID = ""
hideHUGOSupport = false
hjsStyle = "default"
logo = "images/logo.png"
[params.social]
twitter = "clubarteria"
[taxonomies]
tag = "tags"
